export const projects = [
  {
    name: "Chat-Application",
    githubUrl: "https://github.com/Jitesh02/chat-app",
    image: "../../assets/chatapp.png",
    youtube: true,
    youtubeUrl: "https://chat-app-6cqn.onrender.com/",
    projectUrl: "https://chat-app-6cqn.onrender.com/",
    deployed: true,
    category: ["react", "fs"],
  },
  {
    name: "Book Store",
    githubUrl: "https://github.com/Jitesh02/BookStore",
    image: "../../assets/book.png",
    youtube: true,
    youtubeUrl: "https://www.youtube.com/watch?v=pvcLCSIezlA&t=180s",
    projectUrl: "https://bookstorejt.vercel.app/",
    deployed: true,
    category: ["react", "fs"],
  },
  {
    name: "NewsPitara",
    githubUrl: "https://github.com/Jitesh02/BookStore",
    image: "../../assets/newspitara.png",
    youtube: true,
    youtubeUrl: "https://www.youtube.com/watch?v=LbkvSDPV3eg&t=719s",
    category: ["react"],
  },
  {
    name: "Tic-tac-toe",
    githubUrl: "https://github.com/Jitesh02/Tictac",
    image: "../../assets/tic.png",
    youtube: true,
    youtubeUrl: "https://www.youtube.com/watch?v=AP8tZwPzsXA&t=2631s",
    projectUrl: "https://tictac-faqclruyt-jitesh-tripathis-projects.vercel.app/",
    category: ["vanilla"],
    deployed: true,
  },
  {
    name: "LinkIt-Job Board",
    githubUrl: "https://github.com/Jitesh02/",
    image: "../../assets/linkit.png",
    youtube: true,
    youtubeUrl: "https://www.youtube.com/watch?v=n3infyEjLPQ",
    projectUrl: "https://linkit-job-board.vercel.app/",
    deployed: true,
    category: ["react", "fs"],
  },
];
